// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: api/ovsagentpb/agent.proto

package ovsagentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OVSAgent_ListFlows_FullMethodName = "/ovsagentpb.OVSAgent/ListFlows"
)

// OVSAgentClient is the client API for OVSAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OVSAgent defines RPCs for interacting with Open vSwitch.
type OVSAgentClient interface {
	// ListFlows queries ovs flows for a specific bridge, with optional filters.
	ListFlows(ctx context.Context, in *ListFlowsRequest, opts ...grpc.CallOption) (*ListFlowsResponse, error)
}

type oVSAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewOVSAgentClient(cc grpc.ClientConnInterface) OVSAgentClient {
	return &oVSAgentClient{cc}
}

func (c *oVSAgentClient) ListFlows(ctx context.Context, in *ListFlowsRequest, opts ...grpc.CallOption) (*ListFlowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFlowsResponse)
	err := c.cc.Invoke(ctx, OVSAgent_ListFlows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OVSAgentServer is the server API for OVSAgent service.
// All implementations must embed UnimplementedOVSAgentServer
// for forward compatibility.
//
// OVSAgent defines RPCs for interacting with Open vSwitch.
type OVSAgentServer interface {
	// ListFlows queries ovs flows for a specific bridge, with optional filters.
	ListFlows(context.Context, *ListFlowsRequest) (*ListFlowsResponse, error)
	mustEmbedUnimplementedOVSAgentServer()
}

// UnimplementedOVSAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOVSAgentServer struct{}

func (UnimplementedOVSAgentServer) ListFlows(context.Context, *ListFlowsRequest) (*ListFlowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFlows not implemented")
}
func (UnimplementedOVSAgentServer) mustEmbedUnimplementedOVSAgentServer() {}
func (UnimplementedOVSAgentServer) testEmbeddedByValue()                  {}

// UnsafeOVSAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OVSAgentServer will
// result in compilation errors.
type UnsafeOVSAgentServer interface {
	mustEmbedUnimplementedOVSAgentServer()
}

func RegisterOVSAgentServer(s grpc.ServiceRegistrar, srv OVSAgentServer) {
	// If the following call panics, it indicates UnimplementedOVSAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OVSAgent_ServiceDesc, srv)
}

func _OVSAgent_ListFlows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFlowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OVSAgentServer).ListFlows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OVSAgent_ListFlows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OVSAgentServer).ListFlows(ctx, req.(*ListFlowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OVSAgent_ServiceDesc is the grpc.ServiceDesc for OVSAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OVSAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ovsagentpb.OVSAgent",
	HandlerType: (*OVSAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFlows",
			Handler:    _OVSAgent_ListFlows_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/ovsagentpb/agent.proto",
}
