// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: api/ovsagentpb/agent.proto

package ovsagentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListFlowsRequest is the request message for querying ovs flows.
// bridge is the name of the OVS bridge to inspect.
// table, cookie and match_expr are optional filters, corresponding to
// OpenFlow match fields (e.g. "table=1,cookie=0x1234/0xffff").
type ListFlowsRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Bridge string                 `protobuf:"bytes,1,opt,name=bridge,proto3" json:"bridge,omitempty"`
	// Optional table number to filter flows.
	Table uint32 `protobuf:"varint,2,opt,name=table,proto3" json:"table,omitempty"`
	// Optional cookie value to filter flows.
	Cookie uint64 `protobuf:"varint,3,opt,name=cookie,proto3" json:"cookie,omitempty"`
	// Optional raw OpenFlow match expression for advanced filters.
	MatchExpr     string `protobuf:"bytes,4,opt,name=match_expr,json=matchExpr,proto3" json:"match_expr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFlowsRequest) Reset() {
	*x = ListFlowsRequest{}
	mi := &file_api_ovsagentpb_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFlowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFlowsRequest) ProtoMessage() {}

func (x *ListFlowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ovsagentpb_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFlowsRequest.ProtoReflect.Descriptor instead.
func (*ListFlowsRequest) Descriptor() ([]byte, []int) {
	return file_api_ovsagentpb_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ListFlowsRequest) GetBridge() string {
	if x != nil {
		return x.Bridge
	}
	return ""
}

func (x *ListFlowsRequest) GetTable() uint32 {
	if x != nil {
		return x.Table
	}
	return 0
}

func (x *ListFlowsRequest) GetCookie() uint64 {
	if x != nil {
		return x.Cookie
	}
	return 0
}

func (x *ListFlowsRequest) GetMatchExpr() string {
	if x != nil {
		return x.MatchExpr
	}
	return ""
}

// Flow represents a single ovs flow entry in a human-readable form.
// raw is typically the string returned by "ovs-ofctl dump-flows".
type Flow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           string                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flow) Reset() {
	*x = Flow{}
	mi := &file_api_ovsagentpb_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flow) ProtoMessage() {}

func (x *Flow) ProtoReflect() protoreflect.Message {
	mi := &file_api_ovsagentpb_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flow.ProtoReflect.Descriptor instead.
func (*Flow) Descriptor() ([]byte, []int) {
	return file_api_ovsagentpb_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Flow) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

// ListFlowsResponse is the response message containing the list of flows.
type ListFlowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flows         []*Flow                `protobuf:"bytes,1,rep,name=flows,proto3" json:"flows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFlowsResponse) Reset() {
	*x = ListFlowsResponse{}
	mi := &file_api_ovsagentpb_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFlowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFlowsResponse) ProtoMessage() {}

func (x *ListFlowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ovsagentpb_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFlowsResponse.ProtoReflect.Descriptor instead.
func (*ListFlowsResponse) Descriptor() ([]byte, []int) {
	return file_api_ovsagentpb_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ListFlowsResponse) GetFlows() []*Flow {
	if x != nil {
		return x.Flows
	}
	return nil
}

// InstallStaticARPBindingRequest is the request message for installing a static ARP binding.
type InstallStaticARPBindingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the OVS bridge.
	Bridge string `protobuf:"bytes,1,opt,name=bridge,proto3" json:"bridge,omitempty"`
	// Input port on which ARP packets are received.
	InPort uint32 `protobuf:"varint,2,opt,name=in_port,json=inPort,proto3" json:"in_port,omitempty"`
	// IPv4 address for the ARP SPA (e.g. "192.168.1.100").
	Ip string `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	// MAC address for the ARP SHA (e.g. "aa:bb:cc:dd:ee:01").
	Mac           string `protobuf:"bytes,4,opt,name=mac,proto3" json:"mac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallStaticARPBindingRequest) Reset() {
	*x = InstallStaticARPBindingRequest{}
	mi := &file_api_ovsagentpb_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallStaticARPBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallStaticARPBindingRequest) ProtoMessage() {}

func (x *InstallStaticARPBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ovsagentpb_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallStaticARPBindingRequest.ProtoReflect.Descriptor instead.
func (*InstallStaticARPBindingRequest) Descriptor() ([]byte, []int) {
	return file_api_ovsagentpb_agent_proto_rawDescGZIP(), []int{3}
}

func (x *InstallStaticARPBindingRequest) GetBridge() string {
	if x != nil {
		return x.Bridge
	}
	return ""
}

func (x *InstallStaticARPBindingRequest) GetInPort() uint32 {
	if x != nil {
		return x.InPort
	}
	return 0
}

func (x *InstallStaticARPBindingRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *InstallStaticARPBindingRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

// InstallStaticARPBindingResponse contains textual representations of the installed flows.
type InstallStaticARPBindingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flows         []*Flow                `protobuf:"bytes,1,rep,name=flows,proto3" json:"flows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallStaticARPBindingResponse) Reset() {
	*x = InstallStaticARPBindingResponse{}
	mi := &file_api_ovsagentpb_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallStaticARPBindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallStaticARPBindingResponse) ProtoMessage() {}

func (x *InstallStaticARPBindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ovsagentpb_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallStaticARPBindingResponse.ProtoReflect.Descriptor instead.
func (*InstallStaticARPBindingResponse) Descriptor() ([]byte, []int) {
	return file_api_ovsagentpb_agent_proto_rawDescGZIP(), []int{4}
}

func (x *InstallStaticARPBindingResponse) GetFlows() []*Flow {
	if x != nil {
		return x.Flows
	}
	return nil
}

// RemoveStaticARPBindingRequest is the request message for removing a static ARP binding.
type RemoveStaticARPBindingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the OVS bridge.
	Bridge string `protobuf:"bytes,1,opt,name=bridge,proto3" json:"bridge,omitempty"`
	// Input port on which ARP packets are received.
	InPort uint32 `protobuf:"varint,2,opt,name=in_port,json=inPort,proto3" json:"in_port,omitempty"`
	// IPv4 address for the ARP SPA (e.g. "192.168.1.100").
	Ip string `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	// MAC address for the ARP SHA (e.g. "aa:bb:cc:dd:ee:01").
	Mac           string `protobuf:"bytes,4,opt,name=mac,proto3" json:"mac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveStaticARPBindingRequest) Reset() {
	*x = RemoveStaticARPBindingRequest{}
	mi := &file_api_ovsagentpb_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveStaticARPBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveStaticARPBindingRequest) ProtoMessage() {}

func (x *RemoveStaticARPBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ovsagentpb_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveStaticARPBindingRequest.ProtoReflect.Descriptor instead.
func (*RemoveStaticARPBindingRequest) Descriptor() ([]byte, []int) {
	return file_api_ovsagentpb_agent_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveStaticARPBindingRequest) GetBridge() string {
	if x != nil {
		return x.Bridge
	}
	return ""
}

func (x *RemoveStaticARPBindingRequest) GetInPort() uint32 {
	if x != nil {
		return x.InPort
	}
	return 0
}

func (x *RemoveStaticARPBindingRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RemoveStaticARPBindingRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

// RemoveStaticARPBindingResponse is an empty response for successful removal.
type RemoveStaticARPBindingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveStaticARPBindingResponse) Reset() {
	*x = RemoveStaticARPBindingResponse{}
	mi := &file_api_ovsagentpb_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveStaticARPBindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveStaticARPBindingResponse) ProtoMessage() {}

func (x *RemoveStaticARPBindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ovsagentpb_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveStaticARPBindingResponse.ProtoReflect.Descriptor instead.
func (*RemoveStaticARPBindingResponse) Descriptor() ([]byte, []int) {
	return file_api_ovsagentpb_agent_proto_rawDescGZIP(), []int{6}
}

var File_api_ovsagentpb_agent_proto protoreflect.FileDescriptor

const file_api_ovsagentpb_agent_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/ovsagentpb/agent.proto\x12\n" +
	"ovsagentpb\"w\n" +
	"\x10ListFlowsRequest\x12\x16\n" +
	"\x06bridge\x18\x01 \x01(\tR\x06bridge\x12\x14\n" +
	"\x05table\x18\x02 \x01(\rR\x05table\x12\x16\n" +
	"\x06cookie\x18\x03 \x01(\x04R\x06cookie\x12\x1d\n" +
	"\n" +
	"match_expr\x18\x04 \x01(\tR\tmatchExpr\"\x18\n" +
	"\x04Flow\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\tR\x03raw\";\n" +
	"\x11ListFlowsResponse\x12&\n" +
	"\x05flows\x18\x01 \x03(\v2\x10.ovsagentpb.FlowR\x05flows\"s\n" +
	"\x1eInstallStaticARPBindingRequest\x12\x16\n" +
	"\x06bridge\x18\x01 \x01(\tR\x06bridge\x12\x17\n" +
	"\ain_port\x18\x02 \x01(\rR\x06inPort\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x10\n" +
	"\x03mac\x18\x04 \x01(\tR\x03mac\"I\n" +
	"\x1fInstallStaticARPBindingResponse\x12&\n" +
	"\x05flows\x18\x01 \x03(\v2\x10.ovsagentpb.FlowR\x05flows\"r\n" +
	"\x1dRemoveStaticARPBindingRequest\x12\x16\n" +
	"\x06bridge\x18\x01 \x01(\tR\x06bridge\x12\x17\n" +
	"\ain_port\x18\x02 \x01(\rR\x06inPort\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x10\n" +
	"\x03mac\x18\x04 \x01(\tR\x03mac\" \n" +
	"\x1eRemoveStaticARPBindingResponse2\xb9\x02\n" +
	"\bOVSAgent\x12H\n" +
	"\tListFlows\x12\x1c.ovsagentpb.ListFlowsRequest\x1a\x1d.ovsagentpb.ListFlowsResponse\x12r\n" +
	"\x17InstallStaticARPBinding\x12*.ovsagentpb.InstallStaticARPBindingRequest\x1a+.ovsagentpb.InstallStaticARPBindingResponse\x12o\n" +
	"\x16RemoveStaticARPBinding\x12).ovsagentpb.RemoveStaticARPBindingRequest\x1a*.ovsagentpb.RemoveStaticARPBindingResponseB-Z+github.com/Sh1n3zZ/ovs-agent/api/ovsagentpbb\x06proto3"

var (
	file_api_ovsagentpb_agent_proto_rawDescOnce sync.Once
	file_api_ovsagentpb_agent_proto_rawDescData []byte
)

func file_api_ovsagentpb_agent_proto_rawDescGZIP() []byte {
	file_api_ovsagentpb_agent_proto_rawDescOnce.Do(func() {
		file_api_ovsagentpb_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ovsagentpb_agent_proto_rawDesc), len(file_api_ovsagentpb_agent_proto_rawDesc)))
	})
	return file_api_ovsagentpb_agent_proto_rawDescData
}

var file_api_ovsagentpb_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_ovsagentpb_agent_proto_goTypes = []any{
	(*ListFlowsRequest)(nil),                // 0: ovsagentpb.ListFlowsRequest
	(*Flow)(nil),                            // 1: ovsagentpb.Flow
	(*ListFlowsResponse)(nil),               // 2: ovsagentpb.ListFlowsResponse
	(*InstallStaticARPBindingRequest)(nil),  // 3: ovsagentpb.InstallStaticARPBindingRequest
	(*InstallStaticARPBindingResponse)(nil), // 4: ovsagentpb.InstallStaticARPBindingResponse
	(*RemoveStaticARPBindingRequest)(nil),   // 5: ovsagentpb.RemoveStaticARPBindingRequest
	(*RemoveStaticARPBindingResponse)(nil),  // 6: ovsagentpb.RemoveStaticARPBindingResponse
}
var file_api_ovsagentpb_agent_proto_depIdxs = []int32{
	1, // 0: ovsagentpb.ListFlowsResponse.flows:type_name -> ovsagentpb.Flow
	1, // 1: ovsagentpb.InstallStaticARPBindingResponse.flows:type_name -> ovsagentpb.Flow
	0, // 2: ovsagentpb.OVSAgent.ListFlows:input_type -> ovsagentpb.ListFlowsRequest
	3, // 3: ovsagentpb.OVSAgent.InstallStaticARPBinding:input_type -> ovsagentpb.InstallStaticARPBindingRequest
	5, // 4: ovsagentpb.OVSAgent.RemoveStaticARPBinding:input_type -> ovsagentpb.RemoveStaticARPBindingRequest
	2, // 5: ovsagentpb.OVSAgent.ListFlows:output_type -> ovsagentpb.ListFlowsResponse
	4, // 6: ovsagentpb.OVSAgent.InstallStaticARPBinding:output_type -> ovsagentpb.InstallStaticARPBindingResponse
	6, // 7: ovsagentpb.OVSAgent.RemoveStaticARPBinding:output_type -> ovsagentpb.RemoveStaticARPBindingResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_ovsagentpb_agent_proto_init() }
func file_api_ovsagentpb_agent_proto_init() {
	if File_api_ovsagentpb_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ovsagentpb_agent_proto_rawDesc), len(file_api_ovsagentpb_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ovsagentpb_agent_proto_goTypes,
		DependencyIndexes: file_api_ovsagentpb_agent_proto_depIdxs,
		MessageInfos:      file_api_ovsagentpb_agent_proto_msgTypes,
	}.Build()
	File_api_ovsagentpb_agent_proto = out.File
	file_api_ovsagentpb_agent_proto_goTypes = nil
	file_api_ovsagentpb_agent_proto_depIdxs = nil
}
